[tool.poetry]
name = "wordfinder"
version = "0.1.0"
description = ""
authors = ["Sebastian Ullrich <sebastian.ullrich@deepsource.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
